#!/bin/bash

# Get the directory where THIS script is located
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

# Define paths relative to the script location
INPUT_FILE="$SCRIPT_DIR/../themes/tokyonight.conf"
OUTPUT_FILE="$SCRIPT_DIR/../../waybar/colors.css"

# --- Header ---
echo "/* -------------------------------------------------------------------------- */" > "$OUTPUT_FILE"
echo "/*  Tokyo Night Colors - Auto-generated from Hyprland Config                 */" >> "$OUTPUT_FILE"
echo "/*  DO NOT EDIT THIS FILE DIRECTLY. Run the generation script instead.       */" >> "$OUTPUT_FILE"
echo "/* -------------------------------------------------------------------------- */" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Extract variables and format them for CSS
grep '_rgba =' "$INPUT_FILE" | sed 's/\$//g' | while read -r line; do
    # Get the name and replace underscores with hyphens (e.g., bg_dark_rgba -> bg-dark-rgba)
    name=$(echo "$line" | cut -d' ' -f1 | tr '_' '-')
    
    # Get the hex value inside the rgba() part (e.g., 7aa2f7ee)
    hex_val=$(echo "$line" | grep -oP 'rgba\(\K[^)]+')
    
    # Ensure we have a valid hex string before proceeding
    if [[ -z "$hex_val" ]]; then continue; fi

    # Split the hex into Red, Green, Blue, and Alpha components
    r_hex=${hex_val:0:2}
    g_hex=${hex_val:2:2}
    b_hex=${hex_val:4:2}
    a_hex=${hex_val:6:2}

    # Convert Hex to Decimal
    r_dec=$((16#$r_hex))
    g_dec=$((16#$g_hex))
    b_dec=$((16#$b_hex))
    a_dec_raw=$((16#$a_hex))
    
    # Convert alpha to a float using 'bc'
    a_dec_raw_float=$(echo "scale=2; $a_dec_raw / 255" | bc)

    # --- THE FIX: Force leading zero using printf ---
    # This takes the output of bc and ensures it looks like 0.93 instead of .93
    a_dec=$(printf "%.2f" "$a_dec_raw_float")

    # Write the GTK-friendly @define-color line
    # Added a comment for each line showing the source name
    echo "@define-color $name rgba($r_dec, $g_dec, $b_dec, $a_dec);" >> "$OUTPUT_FILE"
done

echo "Success: Colors generated in $OUTPUT_FILE"