# =============================================================================
# HYPRLAND
# =============================================================================

$projectDir = ~/ProjectMambo/MamboDot
$hyprDir = $projectDir/dot/hypr/.config/hypr
$scriptDir = $projectDir/script/hypr

monitor = ,preferred,auto,1
source = $hyprDir/variables.conf
source = $hyprDir/themes/$theme
source = $hyprDir/exec.conf
source = $hyprDir/general.conf
source = $hyprDir/keybinds.conf
source = $hyprDir/windowrules.conf
