$PROJECT_DIR = ~/ProjectMambo/MamboDot/dot/hypr/.config/hypr
source = $PROJECT_DIR/themes/mamboorchedark.conf
source = $PROJECT_DIR/themes/mambooutbackdark.conf

background {
    monitor =
    path = $PROJECT_DIR/wallpapers/wallpaperflare.com_wallpaper(2).jpg
}

input-field {
    monitor =
    size = 400, 50
    rounding = 0
    outline_thickness = 3
    dots_size = 0.27
    dots_spacing = 0.3
    dots_rounding = -2 
    dots_center = true
    outer_color = $brand
    inner_color = $canyon_flash
    font_color = $brand
    check_color = $success
    fail_color = $crimson_creek
    capslock_color = $warning
    numlock_color = $berry_bramble
    bothlock_color = $eucalyptus_smoke
    fade_on_empty = false
    font_family = MamboFont
    placeholder_text = <span font_size="20pt"><i><b>Input Password...</b></i></span>
    fail_text = <span font_size="20pt"><i><b>$FAIL ($ATTEMPTS)</b></i></span>
    position = 0, 50
    halign = center
    valign = bottom
}

label {
    monitor =
    text = cmd[update:0] printf "%s\n%s" "$USER" "$TIME" | awk '{print toupper($0)}'
    text_align = center
    color = $brand
    font_family = MamboFont
    font_size = 50
    position = 0, -80
    halign = center
    valign = top
}