# =============================================================================
# HYPRLAND
# =============================================================================

$projectDir = ~/ProjectMambo/MamboDot
$hyprDir = $projectDir/dot/hypr/.config/hypr
$scriptDir = $hyprDir/script

monitor = ,preferred,auto,1
source = $hyprDir/variables.conf
source = $hyprDir/themes/tokyonight.conf
source = $hyprDir/exec.conf
source = $hyprDir/general.conf
source = $hyprDir/keybinds.conf
source = $hyprDir/windowrules.conf
