# =============================================================================
# VARIABLES
# =============================================================================

$terminal = kitty
$browser = zen-browser
$fileManager = dolphin
$notesEditor = obsidian
$codeEditor = code

$scratchpadName = "minimized"
$theme = mamboheritage.conf

$wsScript = $scriptDir/workspace.sh