# =============================================================================
# VARIABLES
# =============================================================================

$terminal = kitty
$browser = zen-browser
$fileManager = dolphin
$notesEditor = obsidian
#$settings =

$scratchpadName = "minimized"
$theme = mamboheritage.conf

$wsScript = $scriptDir/workspace.sh