# =============================================================================
# VARIABLES
# =============================================================================

$browser = zen-browser
$fileManager = dolphin
$notesEditor = obsidian
$terminal = kitty
#$settings =

$scratchpadName = "minimized"

$wsScript = $scriptDir/workspace.sh