# =============================================================================
# WINDOW RULES
# =============================================================================

# --- FLOATING ---
windowrule = border_color rgba($redAlphaee) rgba($blueAlphaee) 45deg, match:float true

# --- PINNED ---
windowrule = border_color rgba($aquaAlphaee) rgba($yellowAlphaee) 45deg, match:pin true