# =============================================================================
# WINDOW RULES
# =============================================================================

# --- FLOATING ---
windowrule = border_color $green_a $forest_shadow_a $blue_a 45deg, match:float true

# --- PINNED ---
windowrule = border_color $blue_a $muted_gold_a $yellow_a 20deg, match:pin true