$bg = rgb(241616)
$bg_a = rgba(241616ff)
$bg_dark = rgb(1c1111)
$bg_dark_a = rgba(1c1111ff)
$deep_oak = rgb(3b2a2a)
$deep_oak_a = rgba(3b2a2aff)
$surface = rgb(5e2c31)
$surface_a = rgba(5e2c31ee)
$comment = rgb(765d3f)
$comment_a = rgba(765d3fff)
$fg = rgb(e9c5aa)
$fg_a = rgba(e9c5aaff)
$sandstone = rgb(f1d4b9)
$sandstone_a = rgba(f1d4b9ff)
$red = rgb(a93622)
$red_a = rgba(a93622ee)
$rose_wood = rgb(984a42)
$rose_wood_a = rgba(984a42ee)
$purple = rgb(822727)
$purple_a = rgba(822727ee)
$orange = rgb(d3a774)
$orange_a = rgba(d3a774ee)
$copper = rgb(b56952)
$copper_a = rgba(b56952ee)
$muted_gold = rgb(c0955e)
$muted_gold_a = rgba(c0955eee)
$yellow = rgb(e5cb7c)
$yellow_a = rgba(e5cb7cee)
$green = rgb(5c705a)
$green_a = rgba(5c705aee)
$forest_shadow = rgb(3d524a)
$forest_shadow_a = rgba(3d524aee)
$blue = rgb(283e4f)
$blue_a = rgba(283e4fee)
$cyan = rgb(8e9e9b)
$cyan_a = rgba(8e9e9bee)
